/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as ApiPublicHooksRunRemindersRouteImport } from './routes/api/public/hooks/run-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunRemindersRoute =
  ApiPublicHooksRunRemindersRouteImport.update({
    id: '/api/public/hooks/run-reminders',
    path: '/api/public/hooks/run-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/api/public/hooks/run-reminders': typeof ApiPublicHooksRunRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/invoices/new' | '/api/public/hooks/run-reminders'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/invoices/new' | '/api/public/hooks/run-reminders'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/invoices/new'
    | '/api/public/hooks/run-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  ApiPublicHooksRunRemindersRoute: typeof ApiPublicHooksRunRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-reminders': {
      id: '/api/public/hooks/run-reminders'
      path: '/api/public/hooks/run-reminders'
      fullPath: '/api/public/hooks/run-reminders'
      preLoaderRoute: typeof ApiPublicHooksRunRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  ApiPublicHooksRunRemindersRoute: ApiPublicHooksRunRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
